spring:
  application:
    name: approve
  datasource:
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    url: ${DATABASE_HOST_JDBC:jdbc:postgresql://localhost:5432}/approve
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/master.xml
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: ${SERVER_HTTP_PORT:8082}
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs